### ISSUE TITLE
Documentation needs to be improved 

### ISSUE THREAD

**Issue by ghost** [0xGhazy/PyPass#1]
you need to add screenshots and explain in detail for all functions :)

**Comment by 0xGhazy** [comment]
hello @GAbdulWahab, thank you for opening this issue :)

I'll work on standalone `documentation.md` file that contains all details of `PyPass` project with some screenshots.

what about the Docstring inside project's files such as:

```python

# -- Snip --

    def generate_key(self: str) -> None:
        """Function to generate encryption key at first time of running the application."""
        self.key = Fernet.generate_key()
        with open("security_key.key", "wb") as key_obj:
            key_obj.write(self.key)
        print("[+] It's important to take a copy of encryption key :)")

# -- Snip --
```
1- Do you find it sufficient to explain the parts of the code and easy for the contributors to understand the application, or do I need to improve it as well?


In the end, thank you for your help in making the application even better :).

**Comment by ghost** [comment]
you are welcome @0xGhazy , I think  comments is enough, this project is not for the beginner in python it's intermediate 
I have seen project code, some functions I know him others not, but you did not need to explain all functions in code, just main in the project, I wish to contribute in this project but my level in python it's not good
in readme file part "TO-Do"  for anyone make it, or this to you to tell anyone this project need this functions?

**Comment by 0xGhazy** [comment]
Hi @GAbdulWahab,

I wanted to describe each function/method to help those who wanna contribute to this project to get fine with it. to understand the goal of each function and the type of the expected parameter and returns data types.

I'll record a Youtube playlist about how I implemented the core -the basic ideas not going further in each line- of this project, which I think will be a useful starting point for anyone who wanna contribute. waiting for your contribution on this project after this playlist :)

you can contribute by anything even if you think it's a small detail such as misspelling mistakes. you can do it with any type of help (code improvements, code review, design idea...etc.) you are welcome any time :).

Finally, the `ToDo` part from the README.md file
- it's for anyone wanna help, for your case I assigned the documentation task to me cause I understand project cores and ideas, If you had offered to do it, I would have assigned it to you, but unfortunately I have started writing it and I am almost done. But feel free when you find a problem in the project and want to participate in its development, I will gladly accept that.

- indicates which features the project is lacking which I would like to add unless someone can help with that.

nice to meet you here @GAbdulWahab, wish you the best.
