### ISSUE TITLE
Responsive to the user

### ISSUE THREAD

**Issue by habibaelsayed** [0xGhazy/PyPass#14]
- whenever deleting or adding a platform it should show any alert that a deletion/creation happened and the list of passwords gets updated immediately  
- and try decreasing the id after deletion as shown in the screenshot
![Screenshot (78)_LI](https://user-images.githubusercontent.com/76976297/171017404-7b007400-6e13-46a9-a668-cb06d964ca9a.jpg)
n

**Comment by 0xGhazy** [comment]
decreasing the id after deletion is a problem that I try to solve but in vain cause, If we have another table that uses this id as a foreign key it'll be a problem. so we can just fix the accounts list for now.
