### ISSUE TITLE
Adding authentication window when starting the application

### ISSUE THREAD

**Issue by 0xGhazy** [0xGhazy/PyPass#2]
Hey our dear contributors, I'm happy to see you here :)

In this easy/medium issue that aims to improve privacy for user accounts. I suppose to solve this problem the contributor should know the basics of `Python3`, `SQLite3`, and `QtDesigner` and write documentation of the code or contribution he made to help others understand what he has done.

## Problem statement:
at the current time, if the user tries to open the PyPass application the application will open without any authentication layer or process. which threatens the privacy of the user's accounts.

## Suggested solutions:
    Design a login window that appears when the user tries to open the application that asked him to 
    provide a valid username and password that he provides at the setup stage.

### To achieve the previous solution you need to do the following {

- create a new table in the application database `.cores/PyPassdb.sqlite3` to hold the username and password

- ask the user to provide a username and password when he tries to run the application. this step must be in the setup stage `setup.py`

- Design the login window using `QtDesigneer` which uses the `PyQt5` library.

- Implement the authentication function that checks if the provided username and password in the `users` table in the application database

- Implement the method of checking if that is the first time to run the application after turning on the computer. if not the application will run directly without asking him to log in again.

- Creating the documentation that describes the changes made and mentions the technology he uses.
### }

---

- If anything isn't clear to you please inform me, and if you have any other ideas you can describe them below :).

- If you wanna contribute to this issue and don't know how to implement specific steps you can ask me to assign it to you and then help you in finishing your contribution.

All kinds of contributions are accepted even if was a small one. fill it's your place, stay calm and start your coding journey ❤.

**Comment by corey-new** [comment]
Hey @0xGhazy! 
I think this is a great idea for the application. I'd like to be assigned to this issue and get started on implementing this. I would like to ask if there are any specifications or requirements you would like me to follow? Is this like a 2-step authentication protocol or something more custom? Let me know what you think :)

**Comment by 0xGhazy** [comment]
Hey @corey-new, It's nice to see you here 😃

I have updated the description of the issue above, please read it carefully, and if you think you can't complete it 100% let me tell you it's easy + I'm always here to help you with any problem you might face.

One of the goals of the `PyPass` project is that it is a space for everyone to get the experience of contributing to the world of open sources.

Please read the description of the issue above and I am ready to assign it to you whenever you confirm it :)

**Comment by corey-new** [comment]
Awesome @0xGhazy!

I would like to confirm the assignment to this issue. I am pretty familiar with python3, but I'm particularly new to QtDesigner. However, I think I can get over that learning curve since I have basic experience with HTML, CSS, and JavaScript.
I have no questions about the description of requirements as of yet.

**Comment by 0xGhazy** [comment]
It's assigned to you now @corey-new 
Don't forget you can ask for help at any time. :)

**Comment by corey-new** [comment]
Hey @0xGhazy, 
I just submitted a pull request and described the changes there. Unfortunately, due to my time constraints, I was only able to complete half of this issue. I was able to implement the ```user_account_setup()``` method in setup.py and added a ```Users``` table that will hold the accounts to the database ```PyPassdb.sqlite3``` file. 

What still needs to be implemented for this issue:
```
> Design the login window using QtDesigneer which uses the PyQt5 library.

> Implement the authentication function that checks if the provided username and password in the users table in the application database

> Implement the method of checking if that is the first time to run the application after turning on the computer. if not the application will run directly without asking him to log in again.
```

**Comment by 0xGhazy** [comment]
Hey @corey-new 

I reviewed your code and it's merged now :)

Thank you for submitting this code, I only deleted the encryption key file `security_key.key` because it is specific to your version of the program, `so always make sure when you commit the code that you delete the data from the database as well as your encryption key.`

Waiting for your next contribution :)

**Comment by 0xGhazy** [comment]
Hi, @corey-new I Hope you are fine.

the last two couple hours I worked on this issue and I have finished it. if you don't mind i wanna push this changes to the project and close this issue.

if you worked on this issue you can push your changes and I'll add some changes.

please confirm it, I wanna push and close this issue in 8 hours from now.

thank you for reading and for your efforts ❤
