### ISSUE TITLE
Add generate strong password feature.

### ISSUE THREAD

**Issue by ghost** [0xGhazy/PyPass#5]
[+] I edited this description to make it more informative:
----------------------------------------------------------

in this issue, we need to

- Add generating a strong random password and ask the user if he wants to use this password.
- Check for the entered password strength.

This required a modification of the application GUI (Python PyQt5, QtDesigner)
when the user writes a password the application check for its strength level (x/5) and display a message to inform the user if he wants to add a new random strong password instead of the one he entered.

The minimum password strength score is 3 points.
so if the user password gets 4/5 this message will not display for him. or it can be in the text input 
that suggests a random password for the user.

simple code I worked on
```python
    def generate_password(self: "Password") -> str:
        self.random_password = ""
        for password_letter in range(0, 32):
            self.random_password += random.choice(
            string.ascii_uppercase + 
            string.ascii_lowercase +
            string.digits + 
            string.punctuation)
        return self.random_password
```

I'll push this code after Issue #2 is closed

**Comment by 0xGhazy** [comment]
@GAbdulWahab do you mean in adding an account we can generate an 8-bit random password length?

**Comment by ghost** [comment]
@0xGhazy  yes,  I mean  this is a feature behind the main goal of this project 
- [x] save password 
- [x] if he needs to generate a strong password,  he will get random characters, numbers, and punctuation in  6/8-bit length

**Comment by 0xGhazy** [comment]
okay, it's a good idea I think.

I'll work on this feature next week after mid-term exams. :)

**Comment by ghost** [comment]
@0xGhazy  بالتوفيق ان شاء الله
